### ISSUE TITLE
Secret keys do not work on Python 3

### ISSUE THREAD

**Issue by agronholm** [nlsdfnbch/Pysher#24]
This happens because you're passing a unicode string to hmac.new(), but hashes operate on bytestrings, not unicode strings. The result: `TypeError: Unicode-objects must be encoded before hashing`.

**Comment by sanketdiwale** [comment]
I was getting the same error. I think we need to pass the pass the strings to hmac.new as unicode.

I updated the code in pusher.py 's static method _generate_private_key on line 137 from:

`h = hmac.new(secret, subject, hashlib.sha256)`

to 

`h = hmac.new(secret.encode('utf-8'), subject.encode('utf-8'), hashlib.sha256)
`
and it started working for me.

**Comment by agronholm** [comment]
You didn't fix the problem on [line 157](https://github.com/nlsdfnbch/Pysher/blob/master/pysher/pusher.py#L157) where `subject` is a unicode string which is passed to `hmac.new()`.
Does the test suite not cover this function or how did this slip by?

**Comment by deepbrook** [comment]
It apparently does not. The test suite is quite..minimal. It also hasn't seen an update since I forked it.
