### ISSUE TITLE
websocket-client==0.49.0 -> _on_open() missing 1 required positional argument: 'ws' 

### ISSUE THREAD

**Issue by markns** [nlsdfnbch/Pysher#30]
Hey,

The recently released websocket-client==0.49.0 seems to have broken this library:

```
error from callback <bound method Connection._on_open of <Connection(Thread-1, started daemon 123145309167616)>>: _on_open() missing 1 required positional argument: 'ws'
error from callback <bound method Connection._on_message of <Connection(Thread-1, started daemon 123145309167616)>>: _on_message() missing 1 required positional argument: 'message'
```

I see you specify the websocket-client==0.48.0 in the requirements.txt, but that doesn't seem to be respected in the setup.

```
Installing pysher…
Collecting pysher
  Using cached https://files.pythonhosted.org/packages/02/6e/bd0804087be5f432fe2407b8bf00b2abc95f7475274fdc26e82f7d4db0cb/Pysher-0.5.0-py3-none-any.whl
Collecting websocket-client (from pysher)
  Using cached https://files.pythonhosted.org/packages/8c/59/613755914b733a490982e8c9bb666636dc7362c35beafe32df7fbc6bbf4e/websocket_client-0.49.0-py2.py3-none-any.whl
Collecting six (from websocket-client->pysher)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, websocket-client, pysher
Successfully installed pysher-0.5.0 six-1.11.0 websocket-client-0.49.0

Adding pysher to Pipfile's [packages]…
Installing dependencies from Pipfile.lock (0326cd)…
```

**Comment by deepbrook** [comment]
Aye, you are correct. I believe I did not set a version in the setup.py at all. Thanks for reporting this!

**Comment by deepbrook** [comment]
Fixed in `Pysher 0.5.1`

**Comment by devenpatel2** [comment]
I am currently using 0.51.0 and still getting the same error. The error does not occur for 0.47.0.
